language: node_js
node_js:
    - "0.10"
before_install:
    - gem install bundler
    - bundle install
    - gem install scss-lint
    - npm install bower -g
    - npm install karma -g
before_script:
    - bower install
    - gulp dist:build
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
