language: node_js
node_js:
    - "0.10"
env:
    - secure: "oWipxg7y4Qfrnp31pWRuFEKlwZv+V2L+r11D+tx87fsSD1Ve26xBlKgI8uFk9yBFVizloECjPIHyYj5ll17i0eUJt5jn5+NfpeTLcTsZOzJjiLQjYdSozhCxxdiVRXRifJlOKSava7aONQbZtyEiR7+iPVGxwotUCgKuH/00P2g="
before_install:
    - gem install bundler
    - bundle install
    - gem install scss-lint
    - npm install bower -g
    - npm install karma-cli -g
before_script:
    - bower install
    - gulp dist:build
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
